modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Odgug/Vault-Filters/issues"

[[mods]]
modId="vaultfilters"
version="1.16.0"
displayName="Vault Filters"
logoFile="vaultfilters.png"
description='''
Getting tired of sorting gear manually? This simple but powerful mod allows you to filter and sort data heavy vault gear, trinkets, charms, inscriptions and jewels according to your needs and preferences by adding vault related attributes to the already existing attribute filter from the Create mod. The mod adds compatibility for the list and attribute filters with several mods including modular routers, refined storage and sophisticated backpacks. It also removes Create as a research requirement for the filters allowing the mod to be used independently of Create using the compatibility features. Wanna filter omega gear pieces? Put an omega item in the attribute filter and select the new "is of rarity: OMEGA" filter, simple as that!'''
displayURL="https://github.com/Odgug/Vault-Filters"
credits="radimous and JustAHuman-xD"
authors="Joseph Franci"

[[dependencies.vaultfilters]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vaultfilters]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.b,0.5.1.f-332]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vaultfilters]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
